onEvent('recipes', event => {
  const items = [
    'rftoolsbase:machine_frame',
    'thermal:machine_frame',
    'refinedstorage:machine_casing',
    'rftoolsbuilder:builder',
    'appliedenergistics2:controller',
    'appliedenergistics2:drive',
    'waystones:warp_stone',
    'industrialforegoing:machine_frame_pity',
    'easy_villagers:trader',
    'easy_villagers:iron_farm',
    'botania:flight_tiara',
    'mekanism:steel_casing',
    'mekanism:jetpack',
    'buildinggadgets:gadget_building',
    'buildinggadgets:gadget_exchanging',
    'buildinggadgets:gadget_destruction',
    'mekanism:digital_miner',
    'rftoolsutility:crafter1',
    'mekanismgenerators:solar_panel',
    'mekanismgenerators:wind_generator',
    'mininggadgets:mininggadget',
    'mininggadgets:upgrade_empty',
    'mininggadgets:upgrade_three_by_three',
    'refinedstorage:crafter',
    'appliedenergistics2:molecular_assembler',
    'mekanism:formulaic_assemblicator',
    'immersiveengineering:cloche',
    'spawnermod:spawner_key',
    'rftoolsutility:charged_porter',
    'ironjetpacks:advanced_coil',
    'ironjetpacks:basic_coil',
    'pickletweaks:emerald_apple',
    'pickletweaks:diamond_apple',
    'minecraft:golden_apple',
    'darkutils:rune_damage_player',
    'pickletweaks:diamond_paxel',
    'pickletweaks:emerald_paxel',
    'pickletweaks:netherite_paxel',
    'pickletweaks:emerald_helmet',
    'pickletweaks:emerald_leggings',
    'pickletweaks:emerald_chestplate',
    'pickletweaks:emerald_boots',
    'dankstorage:dank_1',
    'dankstorage:dank_2',
    'dankstorage:dank_3',
    'dankstorage:dank_4',
    'dankstorage:dank_5',
    'dankstorage:dank_6',
    'dankstorage:dank_7',
    'engineersdecor:small_solar_panel',
    'darkutils:charm_experience',
    'darkutils:charm_gluttony',
    'darkutils:ender_hopper',
    'botania:gaia_ingot',
    'darkutils:vector_plate_fast',
    'darkutils:vector_plate_extreme',
    'botania:keep_ivy',
    'modularrouters:player_module',
    'dankstorage:1_to_2',
    'dankstorage:2_to_3',
    'dankstorage:3_to_4',
    'dankstorage:4_to_5',
    'dankstorage:5_to_6',
    'dankstorage:6_to_7',
    'modularrouters:blank_module',
    'modularrouters:blank_upgrade',
    'fluxnetworks:flux_block',
    'powah:dielectric_paste',
    'thermal:electrum_nugget',
    'immersiveengineering:nugget_electrum',
    'mekanism:nugget_steel',
    'immersiveengineering:nugget_steel',
    'thermal:constantan_nugget',
    'immersiveengineering:nugget_constantan',
    'mekanism:nugget_uranium',
    'immersiveengineering:nugget_uranium',
    'immersiveengineering:nugget_nickel',
    'thermal:nickel_nugget',
    'immersiveengineering:nugget_silver',
    'thermal:silver_nugget',
    'thermal:lead_nugget',
    'immersiveengineering:nugget_lead',
    'thermal:copper_nugget',
    'mekanism:nugget_copper',
    'immersiveengineering:nugget_copper',
    'create:copper_nugget',
    'mekanism:nugget_bronze',
    'thermal:bronze_nugget',
    'mekanism:nugget_tin',
    'thermal:tin_nugget'
  ];

  // Loop through all items and remove their recipes
  items.forEach(id => event.remove({ output: id }));

  // Remove by name (for simplybackpacks and Botania armor)
  const names = [
    'simplybackpacks:common',
    'simplybackpacks:uncommon',
    'simplybackpacks:rare',
    'simplybackpacks:epic',
    'botania:terrasteel_helmet',
    'botania:terrasteel_chestplate',
    'botania:terrasteel_leggings',
    'botania:terrasteel_boots'
  ];

  names.forEach(name => event.remove({ id: name }));

});
